apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-dm
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: nginx
    spec:
      serviceAccountName: dashboard
      containers:
        - name: nginx
          image: registry.kingdee.com/nginx:1.9
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name: ceph-rbd-volume
              mountPath: "/usr/share/nginx/html"
      volumes:
      - name: ceph-rbd-volume
        persistentVolumeClaim:
          claimName: ceph-claim
      imagePullSecrets:
      - name: regsecret
