apiVersion: v1
kind: Service
metadata:
  name: kdfs-knode
  namespace: kdfs
  labels:
    k8s-app: kdfs-knode
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    k8s-app: kdfs-knode
  type: NodePort
  ports:
  - port: 9270
    nodePort: 9270
