apiVersion: v1
kind: Service
metadata:
  name: kdfs-kserver
  namespace: kdfs
  labels:
    k8s-app: kdfs-kserver
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    k8s-app: kdfs-kserver
  type: NodePort
  ports:
  - port: 9271
    nodePort: 9271
