apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kdfs-kserver
  namespace: kdfs
  labels:
    k8s-app: kdfs-kserver
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      k8s-app: kdfs-kserver
  template:
    metadata:
      labels:
        k8s-app: kdfs-kserver
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"CriticalAddonsOnly", "operator":"Exists"}]'
    spec:
      containers:
      - name: kdfs-kserver
        image: registry.kingdee.com/kserver-test:1.0.2
        resources:
          limits:
            cpu: 1000m
            memory: 1000Mi
          requests:
            cpu: 1000m
            memory: 1000Mi
        ports:
        - containerPort: 9271
        livenessProbe:
          tcpSocket:
            port: 9271
          initialDelaySeconds: 30
          timeoutSeconds: 30
      imagePullSecrets:
      - name: regsecret
