apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kdfs-plugin
  namespace: kdfs
  labels:
    k8s-app: kdfs-plugin
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      k8s-app: kdfs-plugin
  template:
    metadata:
      labels:
        k8s-app: kdfs-plugin
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"CriticalAddonsOnly", "operator":"Exists"}]'
    spec:
      containers:
      - name: kdfs-plugin
        image: registry.kingdee.com/plugin-test:1.0.1
        resources:
          limits:
            cpu: 2000m
            memory: 2000Mi
          requests:
            cpu: 2000m
            memory: 2000Mi
        ports:
        - containerPort: 9272
        livenessProbe:
          tcpSocket:
            port: 9272
          initialDelaySeconds: 30
          timeoutSeconds: 30
      imagePullSecrets:
      - name: regsecret
