# namespace
apiVersion: v1
kind: Namespace
metadata:
  name: "spark-system"
  labels:
    name: "spark-system"
---

# service account
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: kubernetes-spark
  name: kubernetes-spark
  namespace: spark-system
---

# role binding
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-spark
  labels:
    k8s-app: kubernetes-spark
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: kubernetes-spark
  namespace: spark-system
