kind: Service
apiVersion: v1
metadata:
  name: spark-master
  namespace: spark-system
spec:
  type: NodePort
  ports:
    - port: 7077
      targetPort: 7077
      name: spark
    - port: 8080
      targetPort: 8080
      name: http
      nodePort: 30080
  selector:
    component: spark-master
