kind: ReplicationController
apiVersion: v1
metadata:
  name: zeppelin-controller
  namespace: spark-system
spec:
  replicas: 1
  selector:
    component: zeppelin
  template:
    metadata:
      labels:
        component: zeppelin
    spec:
      containers:
        - name: zeppelin
          image: registry.kingdee.com/zeppelin:v0.5.6_v1
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
      serviceAccountName: kubernetes-spark
      imagePullSecrets:
      - name: regsecret
