apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tf-test
  labels:
    k8s-app: tf-test
    kubernetes.io/cluster-service: "true"
  namespace: tensorflow-system
spec:
  selector:
    matchLabels:
      k8s-app: tf-test
  template:
    metadata:
      labels:
        k8s-app: tf-test
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"CriticalAddonsOnly", "operator":"Exists"}]'
    spec:
      containers:
      - name: tf-test
        image: registry.kingdee.com/udacity-assignments:1.0.0
        resources:
          limits:
            cpu: 1000m
            memory: 1000Mi
          requests:
            cpu: 1000m
            memory: 1000Mi
        ports:
        - containerPort: 8888
        livenessProbe:
          tcpSocket:
            port: 8888
          initialDelaySeconds: 30
          timeoutSeconds: 30
      serviceAccountName: kubernetes-tensorflow
      imagePullSecrets:
      - name: regsecret
