apiVersion: v1
kind: Service
metadata:
  name: tf-test
  labels:
    k8s-app: tf-test
    kubernetes.io/cluster-service: "true"
  namespace: tensorflow-system
spec:
  selector:
    k8s-app: tf-test
  type: NodePort
  ports:
  - port: 8888
    nodePort: 30082
